### ISSUE TITLE
Google 翻译和百度翻译出错

### ISSUE THREAD

**Issue by dbafu** [cometlj/hexo-translate-title#1]
解决方法 ：

/Users/dev/dbafu.github.io/node_modules/_hexo-translate-title@1.0.3@hexo-translate-title/lib 

修改 util.js

69  行  修改 Google 翻译网址协议  http  为  https   。

175 行 也修改百度翻译网址为 https  默认为 http  。

我对 github 不太了解，不知道 如何 pr

**Comment by dbafu** [comment]
另外希望在使用说明里面强调  使用的 是根目录的  _config.yml  而不是 theme 里面的

**Comment by cometlj** [comment]
@dbafu 谢谢指出问题，我会做相应修改

**Comment by cometlj** [comment]
已经做相应修改 @dbafu
