### ISSUE TITLE
为什么链接都变成是undefined

### ISSUE THREAD

**Issue by happyjared** [cometlj/hexo-translate-title#12]
Question如题，配置如图，已安装相关node module: npm install hexo-translate-title --save

![wechat _20180628145359](https://user-images.githubusercontent.com/24515549/42017967-44ef5790-7ae3-11e8-93b8-40974eead150.png)

环境：node v10.4.1  npm v6.1.0  hexo-cli v1.1.0
用hexo s本地启动测试，发现以前写好的文章后缀链接都是undefined

**Comment by cometlj** [comment]
看下`source/_posts`文件内有生成的`translate_title: xxxx`吗？看你的配置没有问题，google是否需要配置代理？`hexo g`生成速度如何？

**Comment by happyjared** [comment]
你好，看了一遍你的源代码已经解决了，应该是谷歌翻译不太稳定或者是我这边网络的原因，不需要配置代理，用 `hexo g`目前是有时可以，有时很慢，有时不行。感谢！
