### ISSUE TITLE
无限循环翻译

### ISSUE THREAD

**Issue by holidaypenguin** [cometlj/hexo-translate-title#8]
因为在将翻译好的title重新写到md文件中后，导致hexo-server再次重新编译，将再次执行翻译，希望加入一个比对方法，如果存在的翻译内容将不重新写入md文件

**Comment by cometlj** [comment]
大概明白你的意思。如果title不发生变化，则不执行翻译操作，这几天会做个修正

**Comment by cometlj** [comment]
该问题已经修复，请重新安装下该npm包即可

**Comment by holidaypenguin** [comment]
complete！
